---
title: "DACSS603Final"
author: "Theresa Szczepanski"
desription: "MCAS G9 Science Analysis"
date: "10/22/2023"

format:
  html:
    df-print: paged
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
    
bibliography: references.bib

editor: 
  markdown: 
    wrap: 72
---



```{r}
#| label: setup
#| warning: false
#| message: false

source('dependencies.R')
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


# Introduction

[@knuth84]

Massachusetts Comprehensive Assessment System (MCAS) tests were
introduced as part of the Massachusetts Education Reform Act in 1993
with the goal of providing all students with the skills and knowledge to
thrive in a "complex and changing society" (Papay et. al, 2020 pp, 1).
The MCAS tests are a significant tool for educational equity. Scores on
the Grade 10 Math MCAS test "predict longer-term educational attainments
and labor market success, above and beyond typical markers of student
advantage. For example, among demographically similar students who
attended the same high school and have the same level of ultimate
educational attainment, those with higher MCAS mathematics scores go on
to have much higher average earnings than those with lower scores."
(Papay et. al, 2020 pp 7-10)

In this report, I will analyze the Spring 2022 MCAS Results for students
completing the High School Introductory Physics MCAS at [Rising Tide
Charter Public School](https://risingtide.org/).

The `MCAS_2022` data frame contains performance results from 495
students from Rising Tide on the Spring 2022 [Massachusetts
Comprehensive Assessment System
(MCAS)](https://www.doe.mass.edu/mcas/default.html) tests.

For each student, there are values reported for 256 different variables
which consist of information from four broad categories

-   *Demographic characteristics* of the students themselves (e.g.,
    race, gender, date of birth, town, grade level, years in school,
    years in Massachusetts, and low income, title1, IEP, 504, and EL
    status ).

-   *Key assessment features* including subject, test format, and
    accommodations provided

-   *Performance metrics*: This includes a student's score on individual
    item strands, e.g.,`sitem1`-`sitem42`.

See the `MCAS_2022` data frame summary and **codebook** in the
**appendix** for further details.

The second data set, `SG9_Item`, is $42 \times 9$ and consists of 9
variables with information pertaining to the 42 questions on the 2022
[HS Introductory Physics Item
Report](https://profiles.doe.mass.edu/mcas/mcasitems2.aspx?grade=HS&subjectcode=PHY&linkid=23&orgcode=04830000&fycode=2022&orgtypecode=5&).
The variables can be broken down into 2 categories:

Details about the content of a given test item:

This includes the content `Reporting Category` (MF (motion and forces)
WA (waves), and EN (energy)), the `Standard` from the [2016 STE
Massachusetts Curriculum
Framework](https://www.doe.mass.edu/frameworks/scitech/2016-04.pdf), the
`Item Description` providing the details of what specifically was asked
of students, and the points available for a given question,
`item Possible Points`.

Summary Performance Metrics:

-   For each item, the state reports the percentage of points earned by
    students at Rising Tide, `RT Percent Points`, the percentage of
    available points earned by students in the state,
    `State Percent Points`, and the difference between the percentage of
    points earned by Rising Tide students and the percentage of points
    earned by students in the state, `RT-State Diff`.

-   Lastly, `SG9_CU306Dis` and `SG9_CU306NonDis` are $3 \times 5$
    dataframes consisting of summary performance data by
    `Reporting Category` for students with disabilities and without
    disabilities; most importantly including `RT Percent Points` and
    `State Percent Points`by disability status.

When considering our student performance data, we hope to address the
following broad questions:

```{=html}
<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
```
::: blue
-   What adjustments (if any) should be made at the Tier 1 level, i.e.,
    curricular adjustments for all students in the General Education
    setting?

-   What would be the most beneficial areas of focus for a targeted
    intervention course for students struggling to meet or exceed
    performance expectations?

-   Are there notable differences in student performance for students
    with and without disabilities?
:::

# References
